spring.main.allow-bean-definition-overriding=true

## SpringDataJPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

## Swagger UI custom path
springdoc.swagger-ui.path=/docs

# Security
## key
jwt.secret.access=AA4EmJMiI+Sqh1JkHvCYvB5Xy02TixKihwm5n8PJI3kpsCJoOF24GLBjXN1vh/eeL2WuwXCjO0r3wIVqNLSvDMTWIbalDlbp6paEeeiBT3I7En6uOe8=
jwt.secret.refresh=Q4fcMCriKMpgZPx4nZcqs+9XzUssxO+6/fHYP0rUPY5iXeoLEDY8X2kzHbOn/jcO0zYJbw3tDkoSmxqKnqXjEudRrn8AsAwwYmLli9oIlam4DN1FrIqnUQ==
### Expiration in seconds
jwt.expiration.access=1000
jwt.expiration.refresh=2592000


# Database
## PostgresSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/hackathon
spring.datasource.username=crush
spring.datasource.password=6813
#Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties..hibernate.show_sql=true


# for Put/Patch/Delete request
spring.mvc.hiddenmethod.filter.enabled=true

