jwt.secret.access=AA4EmJMiI+Sqh1JkHvCYvB5Xy02TixKihwm5n8PJI3kpsCJoOF24GLBjXN1vh/eeL2WuwXCjO0r3wIVqNLSvDMTWIbalDlbp6paEeeiBT3I7En6uOe8=
jwt.secret.refresh=Q4fcMCriKMpgZPx4nZcqs+9XzUssxO+6/fHYP0rUPY5iXeoLEDY8X2kzHbOn/jcO0zYJbw3tDkoSmxqKnqXjEudRrn8AsAwwYmLli9oIlam4DN1FrIqnUQ==
spring.main.allow-bean-definition-overriding=true

## Swagger UI custom path
springdoc.swagger-ui.path=/docs

